AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NutriScanOCRRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: NutriScanOCRPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource: arn:aws:s3:::nutriscan-uploads-1/*
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  NutriScanOCRFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - NutriScanOCRRole
        - Arn
      Code:
        S3Bucket: nutriscan-lambda
        S3Key: function.zip
      Runtime: nodejs18.x
      Environment:
        Variables:
          AWS_S3_BUCKET: nutriscan-uploads-1
